tests: Update android targetSdkVersion from 26 to 33
There's an issue with Android 14 that will cause a prompt to display
on the phone  when trying to run tests. This can cause an issue with
CI as the prompt needs to be hit before the tests begin to run.
The prompt displays:
```
This app was built for an older version of Android. It might not work
properly and doesn't include the latest security and privacy
protections.  Check for an update, or contact the app's developer
```

Also, apksigner will be used instead of jarsigner. Builing for newer
version of android will produce  this error when trying to use jarsigner:
```
ERROR: unexpected exception:
_run(/home/lunarg/Android/Sdk/platform-tools/adb -s R5CX21HV9TJ
install -r -g -t
/home/lunarg/.jenkins/workspace/manual-VulkanProfiles/VulkanProfiles/android-build/apk/out/VulkanProfilesLayerTests.apk)
return 1, stdout=Performing Streamed Install, stderr=adb: failed to
install
/home/lunarg/.jenkins/workspace/manual-VulkanProfiles/VulkanProfiles/android-build/apk/out/VulkanProfilesLayerTests.apk:
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Scanning Failed.: No
signature found in package of version 2 or newer for package
com.example.VulkanProfilesLayerTests]
```

Similar issue on VVL and gfxreconstruct:
- https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8045
- https://github.com/LunarG/gfxreconstruct/pull/1079

layer/tests/platforms/android/AndroidManifest.xml:
library/test/platforms/android/AndroidManifest.xml:
- update the android:targetSdkVersion from 26 to 33

layer/tests/CMakeLists.txt:
library/test/CMakeLists.txt
- update to use apksigner instead of jarsigner